services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PASSWORD: TupayaFrigitnaya12312
      DEBUG: "true"
    depends_on:
      - clickhouse
    volumes:
      - ./src:/app/src  # Монтируем для разработки
      # Статические файлы будут доступны через src

volumes:
  clickhouse_data:
